version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres-nest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest-app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: userdb
    depends_on:
      - postgres

volumes:
  postgres_data:
